version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: onlinebookstore-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlinebookstore
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bookstore-network

  app:
    build: .
    container_name: onlinebookstore-app
    restart: always
    ports:
      - "9001:8080"
    depends_on:
      - mysql
    networks:
      - bookstore-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: onlinebookstore-phpmyadmin
    restart: always
    ports:
      - "9002:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - bookstore-network

volumes:
  mysql-data:

networks:
  bookstore-network:

